/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QrReader {
        "afterScan": string;
        "reloadTime": any;
    }
}
export interface QrReaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLQrReaderElement;
}
declare global {
    interface HTMLQrReaderElement extends Components.QrReader, HTMLStencilElement {
    }
    var HTMLQrReaderElement: {
        prototype: HTMLQrReaderElement;
        new (): HTMLQrReaderElement;
    };
    interface HTMLElementTagNameMap {
        "qr-reader": HTMLQrReaderElement;
    }
}
declare namespace LocalJSX {
    interface QrReader {
        "afterScan"?: string;
        "onQrScanned"?: (event: QrReaderCustomEvent<string>) => void;
        "reloadTime"?: any;
    }
    interface IntrinsicElements {
        "qr-reader": QrReader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "qr-reader": LocalJSX.QrReader & JSXBase.HTMLAttributes<HTMLQrReaderElement>;
        }
    }
}
